version: "3.8"

services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ~/Documents/docker_mount_dir/some-mysql:/var/lib/mysql
